[package]
name = "libstratum-format-elf"
description = "ELF container plugin for libstratum (hosted and bare metal)"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
libstratum-core.workspace = true
libstratum-arch.workspace = true
object.workspace = true

[lints]
workspace = true
